spring.application.name=BasicAuthApplication

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/auth_demo
spring.datasource.username=root
spring.datasource.password=toor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT Secret
app.jwt.secret=8dhs93hf82hd94kfdls90d3kf9xckdk2
app.jwt.expiration=86400000
